In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [7]:
covid = pd.read_csv('COVID19.csv')

In [8]:
covid.head()

BodyTemp.  Fatigue  Cough  BodyPain  SoreThroat  BreathingDifficulty  \
0   98.603205        1      0         1           1                    0   
1  102.519485        0      1         1           0                    2   
2  101.799096        1      1         1           2                    1   
3  103.863706        0      1         0           1                    2   
4  102.155484        1      0         0           0                    0   

   Outcome  
0        1  
1        1  
2        1  
3        0  
4        0

In [9]:
covid.shape

(4000, 7)

In [10]:
covid.describe()

BodyTemp.      Fatigue        Cough    BodyPain   SoreThroat  \
count  4000.000000  4000.000000  4000.000000  4000.00000  4000.000000   
mean    101.542417     0.511000     0.507750     0.51150     1.013000   
std       2.025641     0.499941     0.500002     0.49993     0.823104   
min      98.000139     0.000000     0.000000     0.00000     0.000000   
25%      99.793418     0.000000     0.000000     0.00000     0.000000   
50%     101.581286     1.000000     1.000000     1.00000     1.000000   
75%     103.274928     1.000000     1.000000     1.00000     2.000000   
max     104.996821     1.000000     1.000000     1.00000     2.000000   

       BreathingDifficulty     Outcome  
count          4000.000000  4000.00000  
mean              1.016250     0.66275  
std               0.814341     0.47283  
min               0.000000     0.00000  
25%               0.000000     0.00000  
50%               1.000000     1.00000  
75%               2.000000     1.00000  
max               2.000000     1.00000

In [11]:
covid['Outcome'].value_counts()

1    2651
0    1349
Name: Outcome, dtype: int64

In [12]:
covid.groupby('Outcome').mean()

BodyTemp.   Fatigue     Cough  BodyPain  SoreThroat  \
Outcome                                                         
0        101.387417  0.412157  0.358043  0.396590    0.732394   
1        101.621292  0.561298  0.583931  0.569974    1.155790   

         BreathingDifficulty  
Outcome                       
0                   0.781319  
1                   1.135798

In [13]:
X = covid.drop(columns = 'Outcome', axis=1)
Y = covid['Outcome']

In [14]:
print(X)

       BodyTemp.  Fatigue  Cough  BodyPain  SoreThroat  BreathingDifficulty
0      98.603205        1      0         1           1                    0
1     102.519485        0      1         1           0                    2
2     101.799096        1      1         1           2                    1
3     103.863706        0      1         0           1                    2
4     102.155484        1      0         0           0                    0
...          ...      ...    ...       ...         ...                  ...
3995  103.380497        0      1         0           0                    2
3996  103.224004        0      1         1           0                    0
3997  104.103678        0      1         0           0                    1
3998  104.557772        1      0         0           2                    0
3999  100.320435        0      1         1           0                    1

[4000 rows x 6 columns]


In [15]:
print(Y)

0       1
1       1
2       1
3       0
4       0
       ..
3995    1
3996    1
3997    0
3998    1
3999    1
Name: Outcome, Length: 4000, dtype: int64


In [16]:
scaler = StandardScaler()

In [17]:
scaler.fit(X)

StandardScaler()

In [18]:
standardized_data = scaler.transform(X)

In [19]:
print(standardized_data)

[[-1.45118543  0.97823676 -1.01562201  0.97725852 -0.01579585 -1.24809718]
 [ 0.48241035 -1.02224741  0.98461828  0.97725852 -1.23086088  1.20818263]
 [ 0.12673047  0.97823676  0.98461828  0.97725852  1.19926919 -0.01995727]
 ...
 [ 1.26457813 -1.02224741  0.98461828 -1.02327069 -1.23086088 -0.01995727]
 [ 1.48877926  0.97823676 -1.01562201 -1.02327069  1.19926919 -1.24809718]
 [-0.60333262 -1.02224741  0.98461828  0.97725852 -1.23086088 -0.01995727]]


In [20]:
X = standardized_data
Y = covid['Outcome']

In [21]:
print(X)
print(Y)

[[-1.45118543  0.97823676 -1.01562201  0.97725852 -0.01579585 -1.24809718]
 [ 0.48241035 -1.02224741  0.98461828  0.97725852 -1.23086088  1.20818263]
 [ 0.12673047  0.97823676  0.98461828  0.97725852  1.19926919 -0.01995727]
 ...
 [ 1.26457813 -1.02224741  0.98461828 -1.02327069 -1.23086088 -0.01995727]
 [ 1.48877926  0.97823676 -1.01562201 -1.02327069  1.19926919 -1.24809718]
 [-0.60333262 -1.02224741  0.98461828  0.97725852 -1.23086088 -0.01995727]]
0       1
1       1
2       1
3       0
4       0
       ..
3995    1
3996    1
3997    0
3998    1
3999    1
Name: Outcome, Length: 4000, dtype: int64


In [22]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, stratify=Y, random_state=2)

In [23]:
print(X.shape, X_train.shape, X_test.shape)

(4000, 6) (3200, 6) (800, 6)


In [24]:
classifier = svm.SVC(kernel='linear')

In [25]:
classifier.fit(X_train,Y_train)

SVC(kernel='linear')

In [26]:
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [27]:
print("Accuracy score of the training data is: ", training_data_accuracy)

Accuracy score of the training data is:  0.725625


In [28]:
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [29]:
print("Accuracy score of the test data is: ", test_data_accuracy)

Accuracy score of the test data is:  0.7275


In [30]:
input_data = (99.8898582,1,0,0,2,2)
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
std_data = scaler.transform(input_data_reshaped)
print(std_data)
prediction = classifier.predict(std_data)
print(prediction)
if (prediction[0] == 0):
    print("The Person is non-covid")
else:
    print("The person is covid")

[[-0.81592249  0.97823676 -1.01562201 -1.02327069  1.19926919  1.20818263]]
[1]
The person is covid


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [31]:
import pickle

In [32]:
filename = "Covid_model.sav"
pickle.dump(classifier, open(filename, "wb"))

In [33]:
#loading the saved model

loaded_model = pickle.load(open("Covid_model.sav", "rb"))

In [34]:
input_values = (99.820327,1,0,0,2,2)

input_values_as_numpy_array = np.asarray(input_values)
input_values_reshaped = input_values_as_numpy_array.reshape(1,-1)

prediction = loaded_model.predict(input_values_reshaped)
print(prediction)

if (prediction[0] == 0):
    print("The Person is non-Covid")
else:
    print("The person is covid")

[1]
The person is covid


In [36]:
for column in covid:
    print(column)

BodyTemp.
Fatigue
Cough
BodyPain
SoreThroat
BreathingDifficulty
Outcome
